name: Auto Uncompress EPG

on:
  schedule:
    - cron: '0 4 * * *' # Runs automatically every day at 4:00 AM UTC
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and Uncompress File
        run: |
          curl -sL "https://github.com/ferteque/Curated-M3U-Repository/raw/refs/heads/main/epg6.xml.gz" -o mytvlist.xml.gz
          gunzip -f mytvlist.xml.gz

      - name: Commit and Push Updated XML to Repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mytvlist.xml
          git commit -m "Automated daily update" || exit 0
          git push
